CREATE TABLE ALUNO (
    CPF VARCHAR(14) NOT NULL,
    NOME VARCHAR(500) NOT NULL,
    EMAIL VARCHAR(500) NOT NULL,
    CONSTRAINT PK_ALUNO PRIMARY KEY (CPF)
);


CREATE TABLE TELEFONE (
    DDD VARCHAR(2) NOT NULL,
    NUMERO VARCHAR(15) NOT NULL,
    CPF VARCHAR(14),
    CONSTRAINT PK_TELEFONE PRIMARY KEY (DDD, NUMERO),
    CONSTRAINT FK_ALUNO_TELEFONE FOREIGN KEY (CPF) REFERENCES ALUNO
);
